### ISSUE TITLE
Combining with `gf` 

### ISSUE THREAD

**Issue by etrnal70** [willothy/flatten.nvim#85]
**Is your feature request related to a problem? Please describe.**
As i'm using neovim terminal quite extensively, i do often use `gf` command to jump from an error message directly to the filepath. Would be cool to have this integrated too in flatten. Thank you for the plugin too !

**Describe the solution you'd like**
Using `gf` on something like linter output that has a filepath will reuse existing buffer

**Describe alternatives you've considered**
nil

**Additional context**
Linter example
![image](https://github.com/willothy/flatten.nvim/assets/5826834/7b2fefa5-4cad-4f71-8298-7d95230e8024)

**Comment by willothy** [comment]
Hi, glad you like the plugin!

I'm not entirely sure but this should work natively in nvim... it seems to work for me (unrelated to flatten).

If it doesn't however and what I'm experiencing is from another plugin, I think this is outside the scope of what flatten is intended to do. Using `gf` to open a file in the nvim terminal doesn't open a nested instance, so this would be adding a completely separate feature to the plugin.

**Comment by brentd** [comment]
> Using gf to open a file in the nvim terminal doesn't open a nested instance, so this would be adding a completely separate feature to the plugin.

@willothy supporting `gf` in a terminal buffer would be useful for me so that I can have the benefit of the `window: { open = "alternate" }` option for both `nvim ...` as well as `gf`/`gF` when used in a terminal buffer. The consistency would nice. I can't seem to find another plugin that does this. I can see how this feature is a bit orthogonal to flatten's purpose. Any pointers?
